### ISSUE TITLE
Update .py versions of examples

### ISSUE THREAD

**Issue by FilippoOggionni** [tudat-team/tudatpy-examples#8]
As a follow-up task from the developer meeting, @gaffarelj, could you please take care of the following tasks?

- [x] delete the old `.py` examples
- [x] provide new `.py` examples created via automatic conversion of Jupyter notebooks
- [x] add this information (i.e., `.py` examples are provided, but they are converted automatically, so we don't maintain them / assure that everything is fine) to the README

**Comment by gaffarelj** [comment]
I made the conversion and pushed it with 9c658213e661e8afc31738eba04f4973c38c90e2.
I semi-automatically edited the .py examples to still be somewhat clean to read through, and made sure all of them work as expected.

The README has been edited too, but I didn't put the accent too much on the fact that we don't assure that everything is fine (since I did make sure of that in the end).
